# Generated by Django 4.2.4 on 2023-12-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHeadshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=50, unique=True)),
                ('player_name', models.CharField(max_length=50)),
                ('head_shot_url', models.URLField()),
            ],
        ),
    ]
