# Generated by Django 4.2.4 on 2024-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAwards',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(default='N/A', max_length=100)),
                ('accomplishments', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBio',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(default='N/A', max_length=100)),
                ('school', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('height', models.CharField(blank=True, default='N/A', max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, default='N/A', null=True)),
                ('year', models.IntegerField(blank=True, default='N/A', null=True)),
                ('number', models.IntegerField(blank=True, default='N/A', null=True)),
                ('position', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('team_id', models.IntegerField(default=0)),
                ('team_name', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('PTS', models.FloatField(blank=True, default=0, null=True)),
                ('REB', models.FloatField(blank=True, default=0, null=True)),
                ('AST', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playerheadshot',
            name='head_shot_url',
        ),
        migrations.RemoveField(
            model_name='playerheadshot',
            name='id',
        ),
        migrations.AddField(
            model_name='playerheadshot',
            name='background_colour',
            field=models.CharField(blank=True, default='N/A', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='playerheadshot',
            name='player_image_url',
            field=models.URLField(default='https://static.vecteezy.com/system/resources/thumbnails/004/511/281/small_2x/default-avatar-photo-placeholder-profile-picture-vector.jpg'),
        ),
        migrations.AddField(
            model_name='playerheadshot',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerheadshot',
            name='player_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playerheadshot',
            name='player_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
