# Generated by Django 4.2.4 on 2024-09-05 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stats', '0002_careerawards_playerbio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueLeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('leaders', models.JSONField(default=dict)),
            ],
        ),
    ]
