# Generated by Django 4.2.4 on 2024-10-02 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stats', '0004_careerawards_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbio',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
