# Generated by Django 4.1.7 on 2024-11-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0005_playerbio_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerbio",
            name="BLK",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="playerbio",
            name="STL",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="AST",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="PTS",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="playerbio",
            name="REB",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
