# Generated by Django 4.1.7 on 2024-11-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0006_playerbio_blk_playerbio_stl_alter_playerbio_ast_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerbio",
            name="date",
        ),
    ]
