# Generated by Django 4.2.4 on 2024-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EasternConferenceTeams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_full_name', models.CharField(default='N/A', max_length=100)),
                ('team_name', models.CharField(default='N/A', max_length=100)),
                ('team_abbreviated', models.CharField(default='N/A', max_length=10)),
                ('team_city', models.CharField(default='N/A', max_length=100)),
                ('team_logo_url', models.URLField(blank=True, default='https://media.licdn.com/dms/image/v2/C4E0BAQEke_OTftxqtQ/company-logo_200_200/company-logo_200_200/0/1660575300584/national_basketball_association_logo?e=1733356800&v=beta&t=LJiOxzNM9mfdgbHT2akuXDP2oYH3YUMDpypmkObMSyc', null=True)),
                ('team_colour', models.CharField(default='N/A', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Eastern Conference Teams',
            },
        ),
        migrations.CreateModel(
            name='WesternConferenceTeams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_full_name', models.CharField(default='N/A', max_length=100)),
                ('team_name', models.CharField(default='N/A', max_length=100)),
                ('team_abbreviated', models.CharField(default='N/A', max_length=10)),
                ('team_city', models.CharField(default='N/A', max_length=100)),
                ('team_logo_url', models.URLField(blank=True, default='https://media.licdn.com/dms/image/v2/C4E0BAQEke_OTftxqtQ/company-logo_200_200/company-logo_200_200/0/1660575300584/national_basketball_association_logo?e=1733356800&v=beta&t=LJiOxzNM9mfdgbHT2akuXDP2oYH3YUMDpypmkObMSyc', null=True)),
                ('team_colour', models.CharField(default='N/A', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Western Conference Teams',
            },
        ),
    ]
