# Generated by Django 4.2.4 on 2024-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiredPlayers',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('players', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
