# Generated by Django 4.2.4 on 2024-07-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_today', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlogo',
            name='team_colour',
            field=models.CharField(default='#7E354D', max_length=50),
        ),
    ]
