# Generated by Django 4.2.4 on 2024-08-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_today', '0002_teamlogo_team_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlogo',
            name='team_city',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='teamlogo',
            name='team_full_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
