# Generated by Django 4.2.4 on 2024-09-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_today', '0003_teamlogo_team_city_teamlogo_team_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamLogo',
        ),
    ]
